export const flightIcons = {
    "0": "flight_takeoff",
    "1": "flight_land"
};

export const url = "https://api.rasp.yandex.net/v3.0/schedule/";

export const key = "7b33c0fa-d05a-4abc-9c96-dbd269eb76d7";

export const SVXcode = "usss";

export const defaultFlightList = [
    {id: 1, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 2, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 3, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 4, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 5, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 6, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 7, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 8, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 9, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 10, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 11, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 12, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 13, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 14, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 15, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 16, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 17, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 18, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 19, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 20, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 21, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 22, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 23, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 24, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 25, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 26, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 27, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 28, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 29, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 30, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 31, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 32, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 33, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 34, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 35, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 36, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 37, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 38, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 39, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 40, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 41, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 42, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 43, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 44, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 45, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 46, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 47, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 48, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 49, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 50, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 51, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 52, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 53, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 54, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 55, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 56, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 57, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 58, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 59, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 60, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 61, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 62, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 63, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 64, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 65, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 66, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
    {id: 67, departureTime: "18: 00", realDepartureTime: "18: 10", arriveTime: "20: 00", realArriveTime: "20: 10", flight: "123", company:["S1"], status: "Приземлился", delay: true, "from": "Екатеринбург", "to":"Таганрог" },
    {id: 68, departureTime: "18: 10", realDepartureTime: "18: 10", arriveTime: "20: 30", realArriveTime: "20: 20", flight: "125", company:["S2"], status: "Приземлился", delay: false, "from": "Екатеринбург", "to":"Минск" },
    {id: 69, departureTime: "18: 20", realDepartureTime: "18: 20", arriveTime: "22: 00", realArriveTime: "22: 10", flight: "133", company:["S3"], status: "Приземлился", delay: true, "from": "Перьм", "to":"Екатеринбург" },
    {id: 70, departureTime: "18: 30", realDepartureTime: "18: 40", arriveTime: "20: 00", realArriveTime: "20: 00", flight: "523", company:["S4"], status: "Приземлился", delay: false, "from": "Владивосток", "to":"Екатеринбург" },
    {id: 71, departureTime: "18: 50", realDepartureTime: "20: 10", arriveTime: "23: 00", realArriveTime: "00: 10", flight: "323", company:["S5"], status: "В полете", delay: true, "from": "Екатеринбург", "to":"Москва" },
    {id: 72, departureTime: "19: 00", realDepartureTime: "19: 00", arriveTime: "23: 00", realArriveTime: "23: 10", flight: "453", company:["S6"], status: "Приземлился", delay: true, "from": "Москва", "to":"Екатеринбург" },
];
